### ISSUE TITLE
[Question] Segmented AP is a 'AP without radio' after flashing 2.5-beta?

### ISSUE THREAD

**Issue by Calimerorulez** [jjwbruijn/OpenEPaperLink#236] opened 2024-02-25 07:49 UTC
Hi,

Thank you for the constant improvements of this project.

Is it correct that a segmented AP now is a 'AP without radio' in 2.5-beta?

The WebUI is showing that on one of my APs.

If that is so, what's the use of that kind of AP?

**Comment by jonasniesner** [comment] 2024-02-25 08:41
No, that is not correct. Did this AP show online with the previous version of firmware? The use of an AP without radio would be a flasher, but that is likely not what you have. Can you tell us what AP type your have?

**Comment by Calimerorulez** [comment] 2024-02-25 09:08
It is shown as SLT-EM007 Segmented AP, this one:

![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/1130552/7d8c9aac-0b13-4c78-8995-555e9b3bfd0c)

Running 2.07b, it's running fine:

```
env:                OpenEPaperLink_Mini_AP
build date:         2024-01-09 21:39
esp32 version:      2.07b
filesystem version: 2.07b
psram size:         2092655
flash size:         4194304
```

I just flashed it again to 2.5-beta, and now it's showing online. I don't know why. Sorry for the confusion then...

Only thing I noticed just yet, it was running channel 27, now I can't select that anymore, 26 is the highest channel.

**Comment by nlimper** [comment] 2024-02-25 12:11
Channel 27 is not supported on the C6-based AP's, but on your AP it should be displayed...
Can you please open this in your browser and paste the output here?  `http://192.168.178.198/get_ap_config` (replace the ip address for the ip-address of your AP)

**Comment by jonasniesner** [comment] 2024-02-25 12:26
I am facing the same issue with a Segmented AP. But mine has a hardware defect that something with the flashing does not work and I have to delete the AP firmware pack after every update.

**Comment by nlimper** [comment] 2024-02-25 12:34
The detection of 'no radio' is done by detecting if FLASHER_AP_RXD is shorted with FLASHER_AP_TXD.
https://github.com/jjwbruijn/OpenEPaperLink/blob/master/ESP32_AP-Flasher/src/serialap.cpp#L757-L768

Channel 27 is removed from the drop down if a C6 is detected, but I like to see the output of `/get_ap_config`  to check if that's a problem on the javascript-side or the esp32-side.

**Comment by Calimerorulez** [comment] 2024-02-25 13:15
Ok, now it's showing without radio again, after a couple of hours:

![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/1130552/c2532932-8114-4a2b-a51c-2ad750751955)

Output of `/get_ap_config`:

```
{"C6": "1", "savespace": "1", "hasFlasher": "0", "hasBLE": "0", "apstate": "7", 
  "channel": 26,
  "alias": "ap-garage",
  "led": 127,
  "tft": 255,
  "language": 0,
  "maxsleep": 0,
  "stopsleep": 1,
  "preview": 1,
  "lock": 0,
  "wifipower": 34,
  "timezone": "CET-1CEST-2,M3.5.0/02:00:00,M10.5.0/03:00:00",
  "sleeptime1": 0,
  "sleeptime2": 0,
  "ble": 0,
  "repo": "jjwbruijn/OpenEPaperLink",
  "env": "OpenEPaperLink_Mini_AP"
}
```

I manually changed it to channel 26, because the dropdown was empty, that explains.

**Comment by nlimper** [comment] 2024-02-25 14:28
Found the reason for the channel 27 not appearing: the AP always reported the presence of a C6 (which is unable to send on channel 27). Fixed in https://github.com/jjwbruijn/OpenEPaperLink/commit/b03ad07179749a7c698c62fbd1de559f0eaf8c1c
Still unknown why your AP reported to have no radio. Have you been able to reproduce, or was it a one time thing?

**Comment by Calimerorulez** [comment] 2024-02-25 14:46
I flashed 2.5-beta, and the message showed up. Reverted back to 2.07b and it disappeared. Flashed 2.5-beta again, and it shows up.

**Comment by nlimper** [comment] 2024-02-25 16:33
Okay, thanks for the info. I know enough to be able to fix it shortly.

**Comment by Calimerorulez** [comment] 2024-02-25 18:29
For what it's worth, no tags are connecting to this AP. In 2.07b there were.

I don't know if it's related.

**Comment by nlimper** [comment] 2024-02-25 20:40
fixed, https://github.com/jjwbruijn/OpenEPaperLink/commit/7e3e73a06428c85285fc045825a457831dcfb7b2
Will be visible in next release

**Closed by nlimper** 2024-02-25 20:40 UTC

**Comment by Calimerorulez** [comment] 2024-02-26 10:04
@nlimper 

Another thing I noticed about this AP. When it's powercycled, it 'forgets' it's channel and it reverts back to channel 11. Fixed IP address is retained, but also it's wifi network is forgotten.

**Comment by nlimper** [comment] 2024-02-26 10:51
The config is not forgotten, just not populated correctly in the web interface.
Just fixed in https://github.com/jjwbruijn/OpenEPaperLink/commit/c458c6b29ca780c8b9d6b424bbdb933f8da315b3
Forgotten wifi: for that I need more info. Can you reproduce it?

**Comment by Calimerorulez** [comment] 2024-02-26 11:15
Well, it shows channel 11 in the display of the AP too (bottom left corner).

I will try to reproduce the Wifi loss when I get back home in a couple days. I saw it because the IP address it is getting assigned was 000.000.000.000, and then it was broadcasting its accesspoint.

It's vague, I know. I will let you know if I find a way to reproduce.
